# This is a sample workflow file that tests the connection to a Couchbase cluster
# to be used in a Couchbase starter kit project. You can copy this file to your
# project and modify it to suit your framework and language requirements.

name: Test Connection

on:
  workflow_dispatch:

  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GO_COUCHBASE_CONNECTION_STRING: ${{ secrets.GO_COUCHBASE_CONNECTION_STRING }}
  COUCHBASE_DEFAULT_BUCKET: ${{ secrets.COUCHBASE_DEFAULT_BUCKET }}
  GO_COUCHBASE_USERNAME: ${{ secrets.GO_COUCHBASE_USERNAME }}
  GO_COUCHBASE_PASSWORD: ${{ secrets.GO_COUCHBASE_PASSWORD }}
  COUCHBASE_DEFAULT_SCOPE: ${{ secrets.COUCHBASE_DEFAULT_SCOPE }}
  COUCHBASE_USE_CAPELLA: ${{ vars.COUCHBASE_USE_CAPELLA }}
  COUCHBASE_OTLP_ENABLED: ${{ vars.COUCHBASE_OTLP_ENABLED }}

jobs:
  setup:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./starter
